module.exports={
    ...require('./src/utils/validazione'),
    ...require('./src/utils/hash'),
    ...require('./src/utils/dbKeepAlive'),
    ...require('./client/utils'),
    ...require('./src/config/db'),
    ...require('./src/config/cloudinary'),
    ...require('./src/middleware/images'),
    ...require('./src/middleware/rateLimiter'),
    ...require('./src/middleware/errorHandler'),
    ...require('./src/middleware/notFound'),
    ...require('./src/handlers/favicon')
};